version: '3.1'

services:
  client:
    image: 'client'
    build: './apps/indiegente'
    ports:
      - 4203:443
  api:
    image: api
    build: './apps/api'
    command: node ./dist/main.js
    ports:
      - 3002:3002
    restart: unless-stopped
networks:
  default:
    name: nginxproxymanager_default
    external: true
